# Uncomment the next line to define a global platform for your project
platform :ios, '17.6'

def essentials
end

def test_essentials
end

target 'MiniSAPlayground' do
  use_frameworks!
  essentials

  target 'MiniSAPlaygroundTests' do
    inherit! :search_paths
    test_essentials
  end

  target 'MiniSAPlaygroundUITests' do
    test_essentials
  end

end
