# Uncomment the next line to define a global platform for your project
platform :ios, '17.6'

def essentials
  pod 'Alamofire'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxRelay'
  pod 'Kingfisher'
end

def test_essentials
  pod 'RxTest'
  pod 'Quick'
  pod 'Nimble'
  pod 'Nimble-Snapshots'
  pod 'SnapshotTesting'
  pod 'RxBlocking'
end

target 'MiniSAPlayground' do
  use_frameworks!
  essentials

  target 'MiniSAPlaygroundTests' do
    inherit! :search_paths
    test_essentials
  end

  target 'MiniSAPlaygroundUITests' do
    test_essentials
  end

end
